### ISSUE TITLE
Locking Integrity: Lock does not hold in some circumstances

### ISSUE THREAD

**Issue by jhugman** [mozilla-lockbox/lockbox-android#392] opened 2019-01-18 17:40 UTC
The lock still does not hold:

 > If I lock the app, press back, reopen the app from "recent apps" and do this for a couple of times, the Lock screen is not displayed any more, I see and remain in the entry list screen.
 > If I remove the app for "recent apps" (close the app) and then reopen it, Welcome screen is displayed and tapping on Get Started, takes me to Login -> enter password screen. This happens if the app is locked or unlocked, not sure if it is related to this PR.

This comes from review from @ioana-farcas in #349

**Comment by linuxwolf** [comment] 2019-01-18 17:42
This might be a duplicate of #386 and #387

**Comment by devinreams** [comment] 2019-02-15 20:48
>If I lock the app, press back, reopen the app from "recent apps" and do this for a couple of times, the Lock screen is not displayed any more

I cannot reproduce this with Pixel 2 (8.1.) on the latest build (2599, https://github.com/mozilla-lockbox/lockbox-android/commit/e482245a0fc66ad370cb7acef9a9e49e85e0d551) no matter how hard I try.

I always get the "unlock" screen if I background, back button, hard quit, open, back button, repeat.

At some point (cannot reproduce consistently) I got a flash of "No entries found" in the entries list that then quickly returned to the "unlock" screen (no entries leaked/seen). I think that's could be a separate issue from this where we say the "lock" is not staying.

I move we close as fixed at #437 #446 unless someone else encountered it?

**Comment by nickbrandt** [comment] 2019-02-15 21:00
@devinreams I'm having the same findings while testing. Lock is holding up, the only instance I am experiencing some weirdness is when Force/Hard quit, then re-open, I am brought to the "No Entries Found" state briefly, then it transitions back to the Lock screen.

**Comment by devinreams** [comment] 2019-02-15 21:24
>I am brought to the "No Entries Found" state briefly, then it transitions back to the Lock screen.

OK cool, then I think there's just another little bit of "state" shifting happening and will track that at #447 and #360 (maybe related, maybe not).

I think this is closed as "fixed" as we are definitely staying locked now, even when using autofill vs. opening the app itself 🔒

**Comment by sashei** [comment] 2019-02-15 21:25
not experiencing the core issue anymore either. I wonder if the No Entries would be resolved with a separate splash screen as mentioned in the original #435.

**Closed by devinreams** 2019-02-15 21:24 UTC
Labels: MVP, P1, bug, on-deck
