### ISSUE TITLE
Able to bypass lock screen and gain access to app when Lockbox is locked

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockbox/lockbox-android#386] opened 2019-01-17 18:42 UTC
This is related to PR #349 

I am currently still able to bypass the lock screen when the Lockbox app is in a locked state.

Steps to reproduce:
- Lock Lockbox (either select "Lock Now" in nav drawer or let auto-lock timer engage while app is backgrounded)
- Background app (tap home)
- Open Lockbox from recent apps bar
- Brought to Lock Screen ✅ 
- Open App Switcher
- Select Lockbox from recent apps bar
- Brought to Entry List ❌ 

Note: Sometimes after backgrounding and then foregrounding Lockbox, user is directed to the Welcome Screen instead of the Lock Screen

**Comment by changecourse** [comment] 2019-01-17 18:45
Adding as a P1 follow-up to #260

**Comment by ioana-farcas** [comment] 2019-01-25 18:16
Note: I am not able to reproduce this  with the above steps, but I am experiencing something similar, the scenario is described below:
- If, after locking the app, the app is closed (killed or removed from recent apps) and then reopened, the lock state it's not preserved, an empty entry list is displayed, but there is no way to see your entries.
- Pull to refresh will not display the entries, the loading indicator is displayed indefinitely on top of empty entry list view.
- If I lock the app, I am stuck in a loop and I am unable to unlock (issue #327)

**Comment by nickbrandt** [comment] 2019-01-25 18:17
Retested this today on master (build #2247).

I'm still able to bypass the lock screen, though now I am brought to the No Entries Found state, as in issue #387 (related to force quitting app). See screen capture below.

![lock.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a8dfac67964510011279c2f/125516c66e82c728ace21e0d46e49b9928c0cfeb9ffbb049a15ee4d67304722a2d50a77323d6b72bbb442c535f5f4ca9440c0c12adaf9b37b4f46d2ede0356b49b381d66cc2f10a4b2831abb09be248b4d86b3ba8844d2a5.gif)

**Comment by sashei** [comment] 2019-02-15 18:21
I'm no longer able to reproduce this as of #435

**Comment by nickbrandt** [comment] 2019-02-15 20:44
Finding the same thing in testing. No longer able to get to entries, though I am presented with the No Entries Found state, as @devinreams mentions above. That is only shown to me for a few seconds, then goes back to the lock screen.

**Comment by sashei** [comment] 2019-02-15 20:58
@nickbrandt thanks for the testing! I think the issue you're experiencing is captured in #360 and will close this issue as resolved in favor of this one.

**Closed by sashei** 2019-02-15 20:58 UTC
Labels: MVP, P1, backlog, bug

**Comment by devinreams** [comment] 2019-02-15 20:59
I also tested and consider the original problem "fixed".

Filed a new issue (since not specific to this being "fixed" or the others) filed at #447 for "no entries found". Which may or may not be related to the "user has to do a full re-sync" at #360.
