### ISSUE TITLE
Autofill doesn’t appear on forms like it used to

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-android#494] opened 2019-03-08 20:29 UTC
Some apps and sites aren’t prompting with the form fill overlay like it was before the latest XML update landed. Hmm...

**Comment by devinreams** [comment] 2019-03-11 14:53
Example included twitter.com and Twitter app. I had to tap and hit the kebab menu to open the "Autofill" feature instead of it automagically appearing beneath the form fields.

**Comment by sashei** [comment] 2019-03-13 00:57
@devinreams I have now checked out all our earlier versions of autofill, and it looks like Twitter app filling has never worked? however, on current builds from master, autofill works for twitter.com in Focus & Fennec.

**Comment by sashei** [comment] 2019-03-13 23:40
Closing; this is not actually a regression :p

**Closed by sashei** 2019-03-13 23:40 UTC
Labels: MVP, P2, bug, in progress, 💬 feature-autofill
