### ISSUE TITLE
Logins includes actual passwords output in logs

### ISSUE THREAD

**Issue by jhugman** [mozilla-lockbox/lockbox-android#222] opened 2018-11-20 18:37 UTC
Found while implementing #221 

```
D/LoginsAPI: list all
V/libloginsapi_ffi: sync15_passwords_get_all
D/Logins: got list: { /* all the passwords in the account dot json }
```

This is a blocker for release.

**Comment by linuxwolf** [comment] 2018-12-14 19:19
@jhugman @sashei @eliserichards I am not able to reproduce this on `master` nor `244-sync-fixes`.  I also can't seem to find any log statements that start with `got list` in the usual suspect repos (lockbox, android-components, application-services).

If one of you get a chance, could you check to see if you see this statement still?

**Comment by devinreams** [comment] 2018-12-17 22:59
This may be my own misunderstanding, but from all my testing in the simulator today I also couldn't find anything in verbose logcat logs including the phrase 'password(s)' nor 'login(s)'. 🤷‍♂️

**Comment by linuxwolf** [comment] 2018-12-18 15:23
I also cannot:
* find this in logcat -- emulator or on-device; nor
* find anything like this log anywhere in the codebases for lockbox, a-c, nor a-s.

Closing until someone reproduces it.

**Closed by linuxwolf** 2018-12-18 15:23 UTC
Labels: MVP, P1, backlog
