### ISSUE TITLE
Greeted by incorrect screen after login

### ISSUE THREAD

**Issue by bsurd** [mozilla-lockbox/lockbox-android#359] opened 2019-01-09 10:11 UTC
## Steps to reproduce

1. Open Lockbox on any device
2. Tap on "Get Started"
3. Login with a valid username and password.
4. Open the app drawer and swipe to close the app.
5. Tap on the app icon.

### Expected behaviour
The user should be greeted by the Unlock screen.

### Actual behaviour
The user is greeted by the Get Started screen.

### Device and build information
- Sony Xperia Z5 Premium (Android 7.1.1)
- Samsung Galaxy S8 (Android 8)
- Google Pixel (Android 9)
- [Build #2068](https://app.bitrise.io/build/5de084abff2a9e31)

### Notes

- If the autolock timer passes the Unlock screen is shown after the Get Started screen
- [Logcat](https://github.com/mozilla-lockbox/lockbox-android/files/2740347/log.txt)

**Comment by sashei** [comment] 2019-01-09 18:09
I think this is a duplicate of #320 @devinreams

**Comment by devinreams** [comment] 2019-01-09 19:08
Duplicate of #320 

Agreed, thanks @sashei

**Closed by devinreams** 2019-01-09 19:08 UTC
Labels: bug
