### ISSUE TITLE
Unlocking is not working

### ISSUE THREAD

**Issue by bsurd** [mozilla-lockbox/lockbox-android#293] opened 2018-12-19 09:50 UTC
## Steps to reproduce

1. Open Lockbox
2. Tap on "Get Started" and login with any account
3. Tap on the App View button and swipe close the app
4. Reopen the app and tap on Unlock

### Expected behaviour
You are able to unlock the app.

### Actual behaviour
App is stuck at the unlock screen.

### Device and build information
- Nexus 5 (Android 6.0.1)
- Huawei Honor 8 (Android 7)
- Nexus 6P (Android 8.1.0)
- Google Pixel (Android 9)
- [Build #1785](https://app.bitrise.io/build/8d9b6261fed6330c)

### Notes
- If using the Lock Now option from the menu unlocking works in this case
- [Logcat](https://github.com/mozilla-lockbox/lockbox-android/files/2694236/log.txt)
- [Video](https://drive.google.com/open?id=1aJtqa3CrQkklb6VofWZ-ufn17V297hsV)

**Comment by sandysage** [comment] 2019-01-03 18:09
This seems to be a duplicate of #305. Closing as such.

**Closed by sandysage** 2019-01-03 18:09 UTC
Labels: bug
