### ISSUE TITLE
"Can't connect" message needed if the WebView can't see the internet

### ISSUE THREAD

**Issue by jhugman** [mozilla-lockbox/lockbox-android#190] opened 2018-11-07 14:48 UTC
When the user tries to log in (get started) without an internet connection, she is presented with a blank screen.

When the user tries to log in (get started) with a slow internet connection, she is presented with blank screen for quite a while before being presented with the loading spinner.

**Comment by nickbrandt** [comment] 2018-11-07 17:35
@jhugman we have an issue for no internet connection on various screens (#185 ). Does it make sense to close this in favor of that, or would you prefer these be broken out?

**Comment by sandysage** [comment] 2018-12-12 17:55
Closing as a duplicate of #185

**Closed by sandysage** 2018-12-12 17:55 UTC
