### ISSUE TITLE
Using Lockbox with Fenix crashes Lockbox app

### ISSUE THREAD

**Issue by bbinto** [mozilla-lockbox/lockbox-android#583] opened 2019-04-08 11:22 UTC
STR

1) Lockbox official beta installed, trying out linkedin.com (2 entries found in Lockbox)
2) Open Fenix (1.0.1915, GV 68) go to linkedin.com (not signed in)
3) Sign, it shows the 2 linkedin entries after I typed in my email address

Expected behaviour
4) Select the correct Lockbox entry and login successfully

Actual behaviour
4) Notification that Lockbox app crashed

![Screenshot_20190408-071202](https://user-images.githubusercontent.com/122897/55720595-32fc2b00-59cf-11e9-8a2e-860ceac19c6c.png)

/cc @kbrosnan for FYI

**Comment by LittleAngelwings** [comment] 2019-04-13 22:56
Confirm the issue, same to me.. Lockbox crashes when I try to login with Fenix 1.0.1915
Using Samsung Galaxy Tab A (2016) SM-T580 with Stock Android 8.1.0 German Localization

**Comment by devinreams** [comment] 2019-04-19 16:49
I just tested this on Pixel 2, Lockbox 1.0.2 (build 3428) on latest Fenix and cannot reproduce the crash any longer. 😅 

This was likely related to #548 which is now closed.

@bbinto and/or @LittleAngelwings can you please try on the 1.0.2 Alpha/Beta that should appear in the Play Store shortly (if not already)?

**Comment by sandysage** [comment] 2019-05-03 15:13
I think this is probably good now. We can always reopen if this comes up again. Closing.

**Closed by sandysage** 2019-05-03 15:13 UTC
Labels: P1, bug, crash, needs-reproduce, 💬 feature-autofill
