### ISSUE TITLE
Switching from test data to real account still shows test data

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-android#277] opened 2018-12-17 17:08 UTC
Encountered by @changecourse and @sashei so far, noted at https://github.com/mozilla-lockbox/lockbox-android/pull/232#pullrequestreview-185691789

>When I sign in with test data, I am unable to trigger the sync toaster... but when I disconnect from the test account and try to then log in with my personal account instead, I'm actually presented with the test account entries instead of my personal entries. (@sashei didn't we experience something similar on iOS at some point?)

and

>I have experienced similar issues switching from using test data to real data, I have to do a hard uninstall-reinstall cycle every time, so I don't think this is related to this PR necessarily. I haven't filed an issue for that but can do that today if others are having issues!!

Marking as P2 for now since "test data" feature not available to release builds/users.

**Comment by sashei** [comment] 2018-12-17 17:08
I was just starting to file this as well !! too fast for me @devinreams , thanks for capturing this :)

**Comment by changecourse** [comment] 2018-12-17 17:18
We'll also want to bypass the test data entirely and test from one personal account to another, to see if it has more to do with caching a previous account's entries instead of a test data issue.

**Comment by linuxwolf** [comment] 2018-12-20 22:01
The additional entries may be due to a misunderstanding of how `LoginsStorage.reset()` functions.  From a conversation with application-services, the method we are using doesn't actually delete records locally.

There is mozilla/application-services#493 to address our desired behavior for the future, and there may be a workaround available in the interim (i.e., call `reset()` then `wipe()`, making sure `sync()` doesn't get called between those).

**Comment by linuxwolf** [comment] 2019-01-15 21:13
Premature closing of this issue ... reopening until it's confirmed there's no good way to clean up.

**Closed** 2019-04-02 21:38 UTC
Labels: bug, on-deck
